### PR TITLE
fix: ensure the Welcome Tour opens automatically only for the first time

### LINKED ISSUE #23: [revamp] Create a welcome tour
## How to implement the tour

About the implementation aspect: [reactour](https://www.npmjs.com/package/reactour) seems to provide an out of the box component that could be customized later

## What must be highlighted

Maybe @teolemon @alexgarel  or @CharlesNepote will have an opinion on the top

## When do we do the highlight

Long introductions are most of the time boring, so maybe a short one on the first opening and allow a longer one if the user asks for help

### PR DESCRIPTION
**Pull request by sumana2001**
I have added the welcome tour and made sure it opens automatically only for the first time. Please have a look.

Still facing one issue, I cannot understand the structure of the responsive navbar. I am confused about how to add the settings and tour button to it. Please guide me @alexfauquette 

https://user-images.githubusercontent.com/63084088/183091287-1757e420-3c54-4990-85f0-dce10d05959e.mov

Closes #23

### CODE REVIEW

File: src/components/ResponsiveAppBar.jsx [hunk 1]
```diff
@@ -176,23 +177,31 @@ const ResponsiveAppBar = () => {
...
                   </Button>
                 ) : null
               )}
-
           </Box>
-
-            <Button
+          <Box
+            sx={{
+              display: { xs: "none", md: "flex" },
```
Comment (alexfauquette) [inline src/components/ResponsiveAppBar.jsx:189]: The App bar in mobile and desktop are completely different

The desktop app bar starts with 
```jsx
{/* Desktop content */}
          <Box
            sx={{
              display: { xs: "none", md: "flex" },
```

The mobile app bar starts with 
```jsx
 {/* Mobile content */}
          <Box sx={{ flexGrow: 1, display: { xs: "flex", md: "none" } }}>
```

So those modification will have no impact because on `xs` the parent is not displayed
```suggestion
              display: "flex" ,
```

**Review by alexfauquette — COMMENTED** [review]
Nice, impressive how your code quality improved between the to PR

I put a comment about the app bar responsive behavior. I don't know how reactTour will behave since in mobile view, the links to games are not rendered. They are hidden in the left menu

**Comment by sumana2001** [comment]
Yes I am a bit confused about that. Because if we open the menu and show it, it might overlap the actual tour. What do you suggest? I guess we could just show the tour without the markings in mobile view?
> I put a comment about the app bar responsive behavior. I don't know how reactTour will behave since in mobile view, the links to games are not rendered. They are hidden in the left menu

**Comment by alexfauquette** [comment]
@sumana2001 I added `styled-components` library, suprosingly reactour does not work without it, and it's not in the dependencies

I also made a modification commit such that on mobile the tour doe not highlight any element

Feel free to modify it, otherwise It sounds good

**Review by alexfauquette — APPROVED** [review]
